Repository sebinside/StreamAwesome, pull requests merged in 2025-08, with the labels that each got.

#327 Fix font loading (again).
  StreamAwesome/src/components/utils/FontLoader.vue
Labels: bug

#331 refactor: load Font Awesome fonts in composable instead of FontLoader.vue
  StreamAwesome/src/App.vue
  StreamAwesome/src/components/utils/FontLoader.vue
  StreamAwesome/src/composables/useFontLoader.ts
Labels: enhancement, support

#328 refactor: replace `reactive()` with `ref()`
  StreamAwesome/src/components/settings/GeneralOptions.vue
  StreamAwesome/src/components/settings/presets/ClassicPreset.vue
  StreamAwesome/src/components/settings/presets/CustomPreset.vue
  StreamAwesome/src/components/settings/presets/ModernPreset.vue
  StreamAwesome/src/components/settings/presets/NeoPreset.vue
  StreamAwesome/src/stores/icons.ts
Labels: enhancement, support

#349 Minor UI improvements
  StreamAwesome/src/App.vue
  StreamAwesome/src/components/browser/IconBrowser.vue
  StreamAwesome/src/components/utils/AppFooter.vue
  StreamAwesome/src/components/utils/FontLoader.vue
  StreamAwesome/src/logic/fontAwesomeBrowser.ts
Labels: enhancement
